//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductPractic4
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkReport
    {
        public int ID_WorkReport { get; set; }
        public Nullable<int> People_ID { get; set; }
        public Nullable<int> WorkInfo_ID { get; set; }
    
        public virtual People People { get; set; }
        public virtual WorkInfo WorkInfo { get; set; }
    }
}
